- package.json
exec `nyc mocha lib/**/*.spec.js --exit --watch` with `npm run test:dev`
Executes tests on changes to JavaScript in the CWD, and once initially. Saves needing to manually run tests after code changes.
> Add script that runs mocha with --watch

- lib/payment.spec.js
- lib/receipt.js
- lib/receipt.spec.js
- package.json
When we started wrapping the `signature.v` field, we introduced a bug where the wrapping of this field when hashing the receipt, also affected the serialised JSON version of the receipt, which again invalidated the signature field.
> Fixes bug where a signed receipt would return false when checking if signed

- lib/abis/BalanceTracker.json
- lib/abis/ClientFund.json
- lib/abis/DriipSettlement.json
- lib/abis/DriipSettlementChallenge.json
- lib/abis/NullSettlement.json
- lib/abis/NullSettlementChallenge.json
- package.json
Update the addresses to be consistent with https://github.com/hubiinetwork/nahmii-contracts/releases/tag/v1.0-ropsten.8
> Update v8 contract Ropsten addresses

- .nycrc
- lib/balance-tracker-contract.spec.js
- lib/client-fund-contract.spec.js
- lib/driip-settlement.spec.js
- lib/payment.js
- lib/payment.spec.js
- lib/receipt.js
- lib/receipt.spec.js
- lib/settlement.js
- lib/settlement.spec.js
- package.json
BREAKING CHANGE for Receipt and Payment classes!
- Constructor and factory function (#from()) has changed signatures
- Takes either a wallet, provider or null
- Capabilities of object adjust accordingly
- Throws or rejects with explicit errors for operations outside of instance capabilities
> Make wallet or provider an optional parameter for Receipts and Payments

- .eslintrc.json
- .nycrc
- Docs/nahmii-provider.md
- lib/cluster-information.js
- lib/cluster-information.spec.js
- lib/driip-settlement.js
- lib/nahmii-provider.js
- lib/nahmii-provider.spec.js
- lib/null-settlement.js
- lib/utils.js
- lib/utils.spec.js
- lib/wallet.js
- package.json
BREAKING CHANGE to NahmiiProvider.
- Constructor changes signature: new parameters
- Use the async "from()" factory to create it automatically from cluster.
- Remove hardcoding of ropsten URL in provider.
Prepares the SDK so its possible to use on multiple networks/clusters without maintaining multiple versions of the SDK. #33
> Mainnet support

- lib/driip-settlement-challenge-contract.js
- lib/driip-settlement-contract.js
- lib/null-settlement-challenge-contract.js
- lib/null-settlement-contract.js
- lib/wallet/balance-tracker-contract.js
- lib/wallet/client-fund-contract.js
- lib/wallet/erc20-contract.js
- package.json
The popular code bundler [webpack](https://github.com/webpack/webpack) works a little differently to nodejs when parsing `require` statements. It expects that apart from when importing .js files, the file extension should be explicitly defined.
Explicitly defining .json in our ABI imports would improve the out-of-the-box compatibility with many web projects.
> Improve out-of-the-box compatibility with webpack projects

- package.json
Loosen up the version requirement for ethers so "instanceof" checks have a higher likelyhood of working as expected.
> unlock ethers dependency

- Docs/nahmii-event-provider.md
- Docs/receipt.md
- lib/event-provider/index.js
- lib/event-provider/index.spec.js
- lib/payment.js
- lib/receipt.js
- lib/receipt.spec.js
- package.json
- ethers is now a peer dependency
- auto installs peers in separate folder (unless production deployment)
- Added NahmiiEventProvider#dispose()
- Fix missing provider in receipts from NahmiiEventProvider#onNewReceipt()
- Added some property accessors on the Receipt class
- Documentation updates
> Enhancements to receipts and event provider

- Docs/receipt.md
- lib/event-provider/index.spec.js
- lib/payment.js
- lib/payment.spec.js
- lib/receipt.js
- lib/receipt.spec.js
- lib/settlement/driip-settlement.js
- lib/settlement/driip-settlement.spec.js
- lib/settlement/settlement.js
- lib/settlement/settlement.spec.js
- package.json
Update payment/receipt schema:
- Remove global nonce
- Add `data` property under sender property to payments
- Add `operator: {id, data}` property to receipts
Update the hash function for these newly added properties.
> Update payment schema

- Docs/monetary-amount.md
- Docs/payment.md
- lib/event-provider/index.spec.js
- lib/payment.js
- lib/payment.spec.js
- lib/receipt.spec.js
- lib/settlement/driip-settlement.spec.js
- lib/settlement/settlement.spec.js
- package.json
- test-utils/index.js
Adds "senderRef" property to Payment class. New Payments will generate a UUID for sender ref. serialization and de-serialization will encode and decode the sender ref accordingly.
> Adding encoding and decoding of sender data

- lib/payment.js
- lib/payment.spec.js
- package.json
No exception thrown if the is a parse error of sender data during the Payment.from() factory. 
A new Payment instance is returned and it will have a new unique senderRef by default.
> Exception safety

- lib/settlement/driip-settlement.js
- lib/settlement/driip-settlement.spec.js
- package.json
`DriipSettlementByPayment#settlePayment()` has been augmented by the addition of string parameter `standard`. By this update the registration of mapping of token contract address to standard in smart contract _TransferControllerManager_ is not required for the successful call of `DriipSettlement#settleDriipAsPayment()`. See hubiinetwork/nahmii-contracts#401 for details of possible argument values of `standard`.
In this repo `DriipSettlement#settleDriipAsPayment()` is updated with fixed standard argument `'ERC20'`, consistent with the overall assumption herein that all tokens currently are fungible ones of standard ERC20.
> Support new signature of DriipSettlementByPayment#settlePayment()

- lib/settlement/null-settlement.js
- lib/settlement/null-settlement.spec.js
- lib/wallet/wallet.js
- lib/wallet/wallet.spec.js
- package.json
`NullSettlement#settleNull()` of hubiinetwork/nahmii-contracts has been augmented by the addition of string parameter `standard`. By this update the registration of mapping of token contract address to standard in smart contract _TransferControllerManager_ is not required for the successful call of `NullSettlement#settleNull()`. See hubiinetwork/nahmii-contracts#404 for details of possible argument values of `standard`.
In this repo `NullSettlement#settleNull()` is updated with fixed standard argument `'ERC20'`, consistent with the overall assumption herein that all tokens currently are fungible ones of standard ERC20.
Also the calls to contract functions `ClientFund#withdraw()` and `ClientFund#unstage()` are now carried out with standard argument `'ERC20'`. Again by this change the …
> Standard on null settlement, withdrawal and unstage

- Docs/driip-settlement.md
- Docs/null-settlement.md
- Docs/settlement.md
- lib/settlement/driip-settlement-challenge-state-contract.js
- lib/settlement/driip-settlement-challenge-state-contract.spec.js
- lib/settlement/driip-settlement.js
- lib/settlement/driip-settlement.spec.js
- lib/settlement/null-settlement-challenge-state-contract.js
- lib/settlement/null-settlement-challenge-state-contract.spec.js
- lib/settlement/null-settlement.js
- lib/settlement/null-settlement.spec.js
- lib/settlement/settlement.js
- lib/settlement/settlement.spec.js
- package.json
When making a payment or starting a new settlement, it requires the off-chain balance has been synchronised with the latest states of the smart contracts, so as to avoid the potential balance overrun. At the moment, the front-end hubii-core is utilising a fixed time blocker(lock for 30 block confirmations) to prevent any new payments or settlements per currency after started a new settlement. 
This PR will enable the front ends to deprecate such time blocker. It will be more reliable to use this mechanism to ensure the off-chain balance is synchronised as it is checking against the actual states between the off-chain and on-chain instead of using a fixed time blocker at the client side.
The newly created function is currently integrated into the starting settlement process, but it is not …
> Support determining whether the offchain balance has been synchronised since the start of the last settlement

- package.json
This package does not depend on the latest release of _nahmii-contract-abstractions-ropsten_. It includes by `~3.0.1` where it rather should have included by `^3.0.1`.
With this PR the inclusion is updated to `^3.1.0` corresponding to release v1.4.0-ropsten.1 of nahmii-contracts.
> Update include of Ropsten abstractions and bump patch

- lib/settlement/driip-settlement.js
- lib/settlement/driip-settlement.spec.js
- package.json
This PR fixes an issue during checking if the wallet nonce is strictly greater than the one used in the last settlement.
Because the nonce retrieved from the contract are in BigNumber object type, which is not safe to use the operator such as `<=` to do the comparison. Using the JS operators like `<=` can introduce incorrect comparison result.
Instead, it should use the `BigNumber` library's built-in comparison function `lte`.
Issues: 
This issue could lead the SDK to start null settlement when it is supposed to start driip settlement beforehand. If so, it would fail to synchronise contract's active balance with the latest receipt, and the null settlement could fail with a stage amount greater than the current active balance. …
> Fix wallet nonce comparison

- lib/wallet/wallet.js
- package.json
Avoids instantiating BalanceTracker and ClientFund contracts until they are actually used.
Issues: 
This should make it easier to use the Wallet class in situations where a proper provider is not available, such as using wallets in a testing environment, since non-network based features will work without any further action.
> Lazy instantiation

- Docs/nahmii-provider.md
- README.md
- lib/nahmii-provider.js
- lib/nahmii-provider.spec.js
- package.json
Implements the `operatorAddress` property on the NahmiiProvider class. 
The value of this property is determined from the cluster's meta information at the time of constructing the provider (using the `from()` factory function). If you use the constructor of the provider directly you are expected to provide this piece of information if it is required later on. 
Issues: 
* `nahmii-ethereum-address` is now a peer dependency of this package.
> NahmiiProvider#operatorAddress

- lib/settlement/configuration-contract.js
- lib/settlement/configuration-contract.spec.js
- lib/settlement/settlement.js
- lib/settlement/settlement.spec.js
- package.json
When the settlement is disabled on-chain, we need a better way for the clients to know if it is disabled and prevent them from wasting gas costs in attempting to starting new settlements.
Using the `Configuration` contract, the SDK should be able to check if the settlement is disabled or not based on the earliest settlement block number before starting new settlements. It will throw an exception to notify the clients when the settlement is disabled.
Issues: 
> Use Configuration to check if settlement is disabled

- Docs/monetary-amount.md
- lib/monetary-amount.js
- lib/monetary-amount.spec.js
- package.json
Adds toBSON method to the `MonetaryAmount` type so that it can be serialised and stored into MongoDB databases easily.
Issues: 
> Adds toBSON method to MonetaryAmount type

- lib/settlement/driip-settlement.js
- lib/settlement/driip-settlement.spec.js
- package.json
[PR433 of _nahmii-contracts_](https://github.com/hubiinetwork/nahmii-contracts/pull/433) removed the redundant property `done` of driip settlement objects stored by _DriipSettlementState_ contract. This PR updated the SDK accordingly to rely on the remaining `doneBlockNumber` property instead. Non-zero value of `doneBlockNumber` is equivalent to `true` value of the removed `done` property.
Issues: 
> Use settlement property doneBlockNumber to gauge completion

- lib/nahmii-provider.js
- lib/nahmii-provider.spec.js
- package.json
Fixed incomprehensible default error message :"Unexpected token < in JSON at position 0"
Expected something like: "cannot POST /trading/payments (502)"
- [v] The [Contribution Guidelines][1] has been followed
- [v] Tests for the changes have been added and all test pass (`npm test`)
- [v] JSDoc comments have been reviewed and added / updated as needed
- [v] Build (`npm run build`) was run locally and any changes were pushed
- [v] Lint (`npm run lint`) has passed locally and any fixes were made for failures
- [v] Package version number was updated according to semantic rules
- [v] Any changes to upstream dependencies have already been published
> Disallow JSON to parse unkown error messages

- Docs/driip-settlement.md
- lib/settlement/driip-settlement.js
- lib/settlement/driip-settlement.spec.js
- package.json
When a qualified settlement proposal has been stopped, it should be treated as a terminated proposal. So the clients can be aware of the actual proposal status and won't try to stage them.
Issues: 
> Check if driip settlement proposal has been terminated before staging.

- lib/nahmii-request.js
- lib/nahmii-request.spec.js
- package.json
Added timeout to NahmiRequest
https://github.com/hubiinetwork/nahmii-sdk/issues/134
> Added timeout to NahmiiRequest

- lib/contract/index.js
- lib/nahmii-request.spec.js
- package.json
This PR removes the warning that was called when instantiating a contract with the use of constructor of `NahmiiContract` called from descendant contract's constructor. The shift to using `NahmiiContract#from()` is deferred to separate issue.
Issues: 
* #144
> Removal of NahmiiContract constructor warnings

- .nycrc
- Docs/payment.md
- lib/payment.js
- lib/payment.spec.js
- package.json
Extended Payment constructor to allow for  semantic Payment.senderRef.
* Extended Payment constructor
* Added tests
https://github.com/hubiinetwork/nahmii-sdk/issues/147
> Added semantic  Payment senderRef

- .gitignore
- .nycrc
- Docs/fees-claimant.md
- lib/claim/fees-claimant.js
- lib/claim/fees-claimant.spec.js
- lib/claim/token-holder-revenue-fund-contract.js
- lib/claim/token-holder-revenue-fund-contract.spec.js
- lib/claim/token-holder-revenue-fund-contracts-ensemble.js
- lib/claim/token-holder-revenue-fund-contracts-ensemble.spec.js
- lib/contract/index.js
- package.json
This PR enables the support of claiming fees from multiple instances of `TokenHolderRevenueFund` whose contract abstractions are all stored in one version of nahmii contract abstractions package.
Issues: #157
> Token holder revenue fund contracts ensemble

- Docs/fees-claimant.md
- Docs/nahmii-contract.md
- lib/claim/fees-claimant.js
- lib/claim/fees-claimant.spec.js
- lib/claim/token-holder-revenue-fund-contracts-ensemble.js
- lib/claim/token-holder-revenue-fund-contracts-ensemble.spec.js
- package.json
This PR corrects a few items in the spanning of configurations of `TokenHolderRevenueFundContract` instances. Also it adjusts the claimable and withdrawable fees output from functions of `FeesClaimant`.
Issues: #157
> Logics of spanning configuration of TokenHolderRevenueFundContractEnsemble

- Docs/payment.md
- lib/payment.js
- lib/payment.spec.js
- lib/receipt.spec.js
- package.json
- test-utils/index.js
This PR adds support for sender payload embedded into the encoded `sender.data` property. Only string type value of sender payload is allowed. Falsy values are omitted and not embedded into `sender.data`.
Issues: 
> Payment sender payload
