hubiinetwork/nahmii-sdk

- Docs/payment.md
- Docs/striim-provider.md
- Docs/wallet.md
- README.md
- lib/payment.js
- lib/striim-provider.js
- lib/wallet.js
- package.json
Added JSDoc style documentation and a build script to extract and generate the equivalent markdown files.
> Documentation update

- lib/wallet.js
- lib/wallet.spec.js
Changes in the API / currency format was not taken care of.
> Fix show balance command in the CLI

- Docs/nahmii-provider.md
- Docs/receipt.md
- lib/nahmii-provider.js
- lib/nahmii-provider.spec.js
- lib/receipt.js
- lib/receipt.spec.js
- package.json
- Add effectuatePayment to provider.
- Add automatic update of API access token to provider.
> Updates to support new payment engine

- .eslintrc.json
- lib/monetary-amount.js
- lib/monetary-amount.spec.js
- lib/nahmii-provider.js
- lib/nahmii-request.spec.js
- lib/receipt.js
- lib/utils.js
- lib/utils.spec.js
- lib/wallet.js
- package.json
> Configure eslint

- .gitignore
- lib/payment.js
- lib/payment.spec.js
- lib/receipt.js
- lib/receipt.spec.js
- lib/utils.js
- lib/utils.spec.js
- package.json
Aligns the hashes produced by the SDK to the fields used in the current version of the smart contracts.
> Aligns payment/receipt hashes with current smart contract implementation

- lib/dbg.js
- lib/nahmii-provider.js
- lib/wallet.js
- package.json
> Remove unintentional output from the console. 

- Docs/wallet.md
- lib/wallet.js
- lib/wallet.spec.js
- package.json
> Fix incorrect assumption about deposit return value

- Docs/nahmii-provider.md
- lib/nahmii-provider.js
- package.json
> Fix omission in nahmiiProvider.getTransactionConfirmation docs

- Docs/wallet.md
- lib/wallet.js
- lib/wallet.spec.js
- package.json
> Fix non-nahmii wallet functionality

- .eslintrc.json
- lib/payment.spec.js
- lib/receipt.spec.js
- lib/utils.js
- lib/utils.spec.js
- package.json
https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/
Closes #76
> Migrate to new Buffer API

- lib/nahmii-provider.js
- package.json
> Remove uncatchable error, instead log it to console

- lib/settlement/driip-settlement.js
- lib/settlement/driip-settlement.spec.js
- lib/settlement/settlement.js
- lib/settlement/settlement.spec.js
- package.json
Always uses case-insensitive compare between the wallet/currency addresses.
> Fix address comparisons in settlement

- lib/insufficient-funds-error.spec.js
- lib/nahmii-provider.js
- lib/nahmii-provider.spec.js
- lib/nahmii-request.spec.js
- lib/payment.js
- lib/payment.spec.js
- lib/receipt.js
- lib/receipt.spec.js
- lib/settlement/driip-settlement.js
- lib/settlement/driip-settlement.spec.js
- lib/settlement/settlement.js
- lib/utils.js
- lib/wallet/wallet.js
- lib/wallet/wallet.spec.js
- package.json
- test-utils/index.js
Updates dependencies to use latest ropsten and mainnet packages. This is needed to support settlements on mainnet.
Issues: 
* Linted with updated rules
> New contract packages for ropsten & mainnet

- package.json
Add BSON as a peeer dependency and do some cleanup
Issues: 
> cleanup dependencies and add bson as peer dependency

- package.json
This PR updates the dependency of _nahmii-contract-abstractions-ropsten_ to v3.1.1 in order to refer to contracts deployed with _nahmii-contracts@v1.4.0-ropsten.2_ (See the [nahmii-contracts@v1.4.0-ropsten.2](https://github.com/hubiinetwork/nahmii-contracts/releases/tag/v1.4.0-ropsten.2) for details.)
Issues: 
> nahmii-contract-abstractions-ropsten@3.1.1

- package.json
This PR upgrades the dependency on _nahmii-contract-abstractions-ropsten_ to 3.1.3 reflecting the partial deployment of contracts in _nahmii-contracts@1.4.0-ropsten.3.
Issues: 
> Upgrade nahmii-contract-abstractions-ropsten and bump patch

- package.json
This PR updates the dependency of nahmii-contract-abstractions to v2.1.0 in order to refer to contracts deployed with nahmii-contracts@v1.4.0. (See [nahmii-contracts@v1.4.0](https://github.com/hubiinetwork/nahmii-contracts/releases/tag/v1.4.0) for details.)
Issues: 
> nahmii-contract-abstractions@2.1.0

- package.json
Use latest mainnet abstractions.
Issues: 
> Use latest mainnet abstractions

- package.json
This PR updates the dependency of `nahmii-contract-abstractions` to `v2.1.3`.
Issues: 
> Update version of nahmii-contract-abstractions and bump patch

- package.json
Update of contract abstractions packages:
* nahmii-contract-abstractions@2.1.4
* nahmii-contract-abstractions-ropsten@3.1.4
Issues: 
> Update abstractions and bump minor

- package.json
Update dependency on `nahmii-contract-abstractions-ropsten` to `v3.1.6`.
Issues: 
> Update Ropsten abstractions and bump minor

- package.json
> Update mainnet and Ropsten abstractions packages

- Docs/fees-claimant.md
- lib/claim/fees-claimant.js
- lib/claim/fees-claimant.spec.js
- package.json
This PR enables the retrieval of claimable accruals for a pair of wallet and currency
* #154
> Obtained claimable accruals per wallet and currency

- .gitignore
- lib/cluster-information/cluster-information.js
- lib/cluster-information/cluster-information.spec.js
- package.json
- Add http as supported meta-service protocol.
- Minor version bumped
https://github.com/hubiinetwork/nahmii-sdk/issues/162
> Enhancement to meta service access

- README.md
- package.json
Upgrade dependency _npm-install-peers_ and peer-dependency _nahmii-ethereum-address_.
Issues: 
The peer dependency mechanism suffered from recent updates to npm. Version 1.2.2 of _npm-install-peers_ seems to solve known issues on this front.
> Ethereum address and peer dependencies

- Docs/cluster-information.md
- Docs/driip-settlement.md
- Docs/nahmii-provider.md
- Docs/null-settlement.md
- Docs/payment.md
- Docs/receipt.md
- TERMS.md
- lib/cluster-information/cluster-information.js
- lib/cluster-information/cluster-information.spec.js
- lib/nahmii-provider.js
- lib/nahmii-request.spec.js
- lib/payment.js
- lib/receipt.js
- lib/wallet/wallet.spec.js
- package.json
Update following name change of company
Issues: 
> Change from 'hubii' to 'nahmii'

- package.json
Update to npm@7 style management of peer dependencies
> npm@7 peer dependencies
